name: Build ESP32

on:
  pull_request:
  push:
  repository_dispatch:
  release:
    types:
      - created

jobs:

  # ---------------------------------------
  # Build ESP32SX family
  # ---------------------------------------
  ESP:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        board:
        # ----------------------
        # S2 Alphabetical order
        # ----------------------
        - 'adafruit_camera_esp32s2'
        - 'adafruit_feather_esp32s2'
        - 'adafruit_feather_esp32s2_tft'
        - 'adafruit_feather_esp32s2_reverse_tft'
        - 'adafruit_funhouse_esp32s2'
        - 'adafruit_magtag_29gray'
        - 'adafruit_metro_esp32s2'
        - 'adafruit_qtpy_esp32s2'
        - 'artisense_rd00'
        - 'atmegazero_esp32s2'
        - 'bpi_bit_s2'
        - 'bpi_leaf_s2'
        - 'department_of_alchemy_minimain_esp32s2'
        - 'espressif_hmi_1'
        - 'espressif_kaluga_1'
        - 'espressif_saola_1_wroom'
        - 'espressif_saola_1_wrover'
        - 'gravitech_cucumberRIS_v1.1'
        - 'hexky_s2'
        - 'hiibot_iots2'
        - 'lilygo_ttgo_t8_s2'
        - 'lilygo_ttgo_t8_s2_st7789'
        - 'lilygo_ttgo_t8_s2_wroom'
        - 'lolin_s2_mini'
        - 'lolin_s2_pico'
        - 'microdev_micro_s2'
        - 'morpheans_morphesp-240'
        - 'muselab_nanoesp32-s2_wroom'
        - 'muselab_nanoesp32-s2_wrover'
        - 'olimex_esp32s2_devkit_lipo_vB1'
        - 'targett_mcb_wroom'
        - 'targett_mcb_wrover'
        - 'unexpectedmaker_feathers2'
        - 'unexpectedmaker_feathers2_neo'
        - 'unexpectedmaker_tinys2'
        - 'waveshare_esp32_s2_pico_lcd'
        - 'waveshare_esp32s2_pico'
        # ----------------------
        # S3 Alphabetical order
        # ----------------------
        - 'adafruit_feather_esp32s3'
        - 'adafruit_feather_esp32s3_nopsram'
        - 'adafruit_feather_esp32s3_tft'
        - 'adafruit_qtpy_esp32s3'
        - 'bpi_leaf_s3'
        - 'cytron_maker_feather_aiot_s3'
        - 'espressif_esp32s3_devkitc_1'
        - 'espressif_esp32s3_devkitm_1'
        - 'espressif_esp32s3_eye'
        - 'smartbeedesigns_bee_motion_s3'
        - 'smartbeedesigns_bee_s3'
        - 'unexpectedmaker_feathers3'
        - 'unexpectedmaker_pros3'
        - 'unexpectedmaker_tinys3'
    steps:
    - name: Setup Python
      uses: actions/setup-python@v3

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Checkout submodules
      run: git submodule update --init lib/tinyusb lib/uf2

    - name: Set Env
      run: echo BIN_PATH=ports/espressif/_bin/${{ matrix.board }} >> $GITHUB_ENV

    - name: Build
      run: docker run --rm -v $PWD:/project -w /project espressif/idf:release-v4.4  /bin/bash -c "git config --global --add safe.directory /project && make -C ports/espressif/ BOARD=${{ matrix.board }} all self-update copy-artifact"

    - uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.board }}
        path: ${{ env.BIN_PATH }}

    - name: Prepare Release Asset
      if: ${{ github.event_name == 'release' }}
      run: |
        zip -jr tinyuf2-${{ matrix.board }}-${{ github.event.release.tag_name }}.zip ${{ env.BIN_PATH }}
        cp ${{ env.BIN_PATH }}/update-tinyuf2.uf2 update-tinyuf2-${{ matrix.board }}-${{ github.event.release.tag_name }}.uf2

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      if: ${{ github.event_name == 'release' }}
      with:
        files: |
          tinyuf2-${{ matrix.board }}-*.zip
          update-tinyuf2-${{ matrix.board }}-*.uf2
